#!/usr/bin/env ts-node

/**
 * @file recon-cli.ts
 * @description Command-line interface for running on-demand/ad-hoc reconciliation
 * of individual payment streams in the StreamPay application. It validates input arguments,
 * performs the reconciliation against db and on-chain records, outputs structured JSON
 * logs containing correlation/request IDs, and exits with appropriate codes.
 */

import { ReconciliationService } from './reconciliation/reconcile';
import { ReconciliationReport } from './reconciliation/types';

/**
 * Parsing options retrieved from command-line arguments.
 */
interface ReconCliOptions {
  /** The unique ID of the stream to reconcile. */
  streamId: string;
  /** Allowed rounding tolerance in base units. */
  tolerance: bigint;
  /** If true, reports mismatches without modifying or updating the database status. */
  dryRun: boolean;
  /** Request/correlation ID used for end-to-end logging propagation. */
  requestId: string;
}

/**
 * Dependency injection interface for standard output streams.
 * Allows decoupling and unit testing console output.
 */
interface ReconCliDeps {
  error: (line: string) => void;
  log: (line: string) => void;
}

/**
 * Validates and parses a string value into a non-negative BigInt.
 * Throws an descriptive error if validation fails.
 * 
 * @param value Raw string input from arguments or environment.
 * @param flag Name of the flag or option being parsed, for error messages.
 * @returns Parsed BigInt value.
 */
function parsePositiveBigInt(value: string | undefined, flag: string): bigint {
  if (value === undefined) {
    throw new Error(`${flag} is required`);
  }
  const trimmed = value.trim();
  if (!/^\d+$/.test(trimmed)) {
    throw new Error(`${flag} must be a non-negative integer`);
  }
  return BigInt(trimmed);
}

/**
 * Returns the usage instructions for the CLI tool.
 */
function usage(): string {
  return [
    "Usage: ts-node scripts/recon-cli.ts --stream-id <id> [--tolerance <n>] [--dry-run]",
    "",
    "Run reconciliation for a single stream by its ID.",
    "Exits 0 on SUCCESS, 1 on MISMATCH_FOUND or FAILED.",
    "",
    "Required:",
    "  --stream-id <id>    ID of the stream to reconcile",
    "",
    "Optional:",
    "  --tolerance <n>     Tolerance in base units (default: RECONCILE_TOLERANCE env or 0)",
    "  --dry-run           Report mismatches without persisting status",
    "  --help, -h          Show this help",
  ].join("\n");
}

/**
 * Parses command-line arguments into a structured options object.
 * Validates inputs at the boundary.
 * 
 * @param argv Command line arguments (excluding node/script paths).
 * @returns Parsed and validated options.
 */
export function parseReconArgs(argv: string[]): ReconCliOptions {
  let streamId: string | null = null;
  let tolerance: bigint | null = null;
  let dryRun = false;
  // Fallback unique correlation ID if not provided.
  let requestId = `recon-cli-${Date.now().toString(36)}`;

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--stream-id") {
      const value = argv[index + 1];
      if (!value?.trim()) {
        throw new Error("--stream-id must be non-empty");
      }
      streamId = value.trim();
      index += 1;
    } else if (arg === "--tolerance") {
      tolerance = parsePositiveBigInt(argv[index + 1], "--tolerance");
      index += 1;
    } else if (arg === "--dry-run") {
      dryRun = true;
    } else if (arg === "--request-id") {
      const value = argv[index + 1];
      if (!value?.trim()) {
        throw new Error("--request-id must be non-empty");
      }
      requestId = value.trim();
      index += 1;
    } else if (arg === "--help" || arg === "-h") {
      throw new Error(usage());
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  // Validate required inputs
  if (streamId === null) {
    throw new Error("--stream-id is required");
  }

  // Resolve tolerance from environment variable if not specified in CLI arguments
  if (tolerance === null) {
    const envTol = process.env.RECONCILE_TOLERANCE;
    tolerance = envTol !== undefined ? parsePositiveBigInt(envTol, "RECONCILE_TOLERANCE") : 0n;
  }

  return { streamId, tolerance, dryRun, requestId };
}

/**
 * Formats a raw reconciliation report into a safe, serialized JSON structure.
 * Converts BigInt fields inside the report to strings to prevent serialization issues.
 * 
 * @param report Raw report generated by the ReconciliationService.
 * @returns Serializable report object.
 */
function formatReport(report: ReconciliationReport): Record<string, unknown> {
  return {
    timestamp: report.timestamp,
    totalStreamsChecked: report.totalStreamsChecked,
    status: report.status,
    mismatches: report.mismatches.map((m) => ({
      streamId: m.streamId,
      field: m.field,
      dbValue: String(m.dbValue),
      onChainValue: String(m.onChainValue),
      toleranceApplied: m.toleranceApplied,
    })),
    errors: report.errors.map((e) => ({
      streamId: e.streamId,
      error: e.error,
    })),
  };
}

/**
 * Executes the reconciliation process based on CLI input arguments.
 * 
 * @param argv Command line arguments.
 * @param deps Output dependency overrides (defaults to standard console).
 * @returns Exit code (0 for success, 1 for failures/mismatches).
 */
export async function runReconCli(
  argv: string[],
  deps: ReconCliDeps = console,
): Promise<number> {
  let options: ReconCliOptions;
  
  // Boundary validation: Parse and validate input arguments
  try {
    options = parseReconArgs(argv);
  } catch (err) {
    // Write invalid input errors to stderr inside a standardized envelope
    deps.error(
      JSON.stringify({
        error: {
          code: "INVALID_ARGUMENTS",
          message: err instanceof Error ? err.message : String(err),
          request_id: "recon-cli-argument-error",
        },
      }),
    );
    return 1;
  }

  // Instantiate reconciliation service with the specified tolerance level
  const service = new ReconciliationService({
    tolerance: options.tolerance,
  });

  // Run reconciliation and log results
  try {
    const report = await service.runReconciliation({
      streamId: options.streamId,
      dryRun: options.dryRun,
    });

    // Output the report payload wrapped in a structured data envelope with correlation ID
    deps.log(
      JSON.stringify({
        data: formatReport(report),
        request_id: options.requestId,
      }),
    );

    // If report is failed or a mismatch was found, return non-zero exit code
    if (report.status === "FAILED") {
      return 1;
    }
    if (report.status === "MISMATCH_FOUND") {
      return 1;
    }
    return 0;
  } catch (err) {
    // Standardized error logging for unexpected service/execution failures
    deps.error(
      JSON.stringify({
        error: {
          code: "RECONCILIATION_FAILED",
          message: err instanceof Error ? err.message : String(err),
          request_id: options.requestId,
        },
      }),
    );
    return 1;
  }
}

// Execute CLI only when invoked directly
if (require.main === module) {
  runReconCli(process.argv.slice(2)).then(
    (code) => { process.exitCode = code; },
    () => { process.exitCode = 1; },
  );
}
