/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List activity events
         * @description Returns a paginated, cursor-based list of activity events. Events are sorted by (timestamp desc, id desc) for stable ordering. Supports filtering by streamId and event type.
         */
        get: operations["listActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List audit logs
         * @description Returns a paginated list of audit events. Requires audit log access.
         */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Issue a wallet authentication challenge
         * @description Returns a one-time nonce the client must sign with their Stellar private key, then submit to `POST /api/auth/wallet`.
         */
        get: operations["getWalletChallenge"];
        put?: never;
        /**
         * Verify a signed challenge and issue a bearer token
         * @description Wallet login endpoint. Rate-limited to 5 requests per minute per client IP to mitigate brute-force attempts.
         */
        post: operations["verifyWalletSignature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List payment streams (v1, deprecated)
         * @deprecated
         * @description Returns a cursor-paginated list of streams owned by the authenticated identity. **Deprecated** — use `GET /api/v2/streams` instead.
         */
        get: operations["listStreams"];
        put?: never;
        /**
         * Create a payment stream (v1, deprecated)
         * @deprecated
         * @description Creates a new payment stream in `draft` status. **Deprecated** — use `POST /api/v2/streams` instead.
         *
         *     Supplying an `Idempotency-Key` header makes this request idempotent; replaying the same key and body returns the cached response.
         */
        post: operations["createStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search payment streams with FTS and filters
         * @description Performs full-text search across stream fields (id, recipient, memo, label, email, senderAddress, partnerId, token) and filters by status, asset, sender, recipient, and creation date bounds.
         */
        get: operations["searchStreams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for multi-tenant isolation. Must be a non-empty string. */
                "x-tenant-id": string;
            };
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get a payment stream (v1, deprecated)
         * @deprecated
         * @description Returns a single stream by ID in the v1 shape. **Deprecated** — use `GET /api/v2/streams/{id}` instead.
         *
         *     Responses are cached; a cache hit returns `X-Cache: HIT`.
         */
        get: operations["getStream"];
        put?: never;
        /**
         * Update a payment stream (v1, deprecated)
         * @deprecated
         * @description Partially updates a stream by merging the request body fields. **Deprecated** — there is no direct v2 equivalent; update streams via their lifecycle action sub-routes.
         *
         *     The `updatedAt` field is always refreshed. Cache is invalidated on success.
         */
        post: operations["updateStream"];
        /**
         * Delete a payment stream (v1, deprecated)
         * @deprecated
         * @description Permanently deletes a stream. **Deprecated** — use `DELETE /api/v2/streams/{id}` instead.
         *
         *     A stream must be in `draft` or `ended` status before it can be deleted. Attempting to delete an `active` or `paused` stream returns 409. Cache is invalidated on success.
         */
        delete: operations["deleteStream"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{id}/start": {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for multi-tenant isolation. Must be a non-empty string. */
                "x-tenant-id": string;
                /** @description Client-generated key (UUID recommended) to make the request idempotent. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a payment stream (v1, deprecated)
         * @deprecated
         * @description Transitions a stream from `draft` (or `paused`) to `active`, initiating payment disbursements. **Deprecated** — use `POST /api/v2/streams/{id}/start` instead.
         */
        post: operations["startStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{id}/stop": {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for multi-tenant isolation. Must be a non-empty string. */
                "x-tenant-id": string;
                /** @description Client-generated key (UUID recommended) to make the request idempotent. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop a payment stream (v1, deprecated)
         * @deprecated
         * @description Permanently stops a stream, transitioning it to `ended` status. Valid from `active` or `draft` states. This action is irreversible. **Deprecated** — use `POST /api/v2/streams/{id}/stop` instead.
         */
        post: operations["stopStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{id}/pause": {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for multi-tenant isolation. Must be a non-empty string. */
                "x-tenant-id": string;
                /** @description Client-generated key (UUID recommended) to make the request idempotent. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause a payment stream (v1, deprecated)
         * @deprecated
         * @description Temporarily suspends an active stream, transitioning it to `paused` status. Payments are halted and `pausedAt` is recorded until the stream is resumed. Only valid when the stream is `active`. **Deprecated** — use `POST /api/v2/streams/{id}/pause` instead.
         */
        post: operations["pauseStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{id}/settle": {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for multi-tenant isolation. Must be a non-empty string. */
                "x-tenant-id": string;
                /** @description Client-generated key (UUID recommended) to make the request idempotent. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Settle a payment stream (v1, deprecated)
         * @deprecated
         * @description Finalises the stream on Stellar/Soroban, transitioning it to `ended` and recording the settlement transaction. Only valid when the stream is `active` or `paused`. **Deprecated** — use `POST /api/v2/streams/{id}/settle` instead.
         */
        post: operations["settleStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/streams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List payment streams (v2)
         * @description Returns all streams owned by the authenticated user in the v2 shape (`allowed_actions`, `created_at`, `settlement`).
         */
        get: operations["listStreamsV2"];
        put?: never;
        /** Create a payment stream (v2) */
        post: operations["createStreamV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/streams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get a payment stream (v2)
         * @description Returns a single stream by ID in the v2 shape.
         */
        get: operations["getStreamV2"];
        put?: never;
        post?: never;
        /**
         * Delete a payment stream (v2)
         * @description Permanently deletes a stream. The stream must be in `draft` or `ended` status; attempting to delete an `active` or `paused` stream returns 409.
         */
        delete: operations["deleteStreamV2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/streams/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a payment stream
         * @description Transitions a stream from `draft` to `active`, initiating payment disbursements. Only valid when the stream is in `draft` status.
         */
        post: operations["startStreamV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/streams/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop a payment stream
         * @description Permanently stops a stream, transitioning it to `ended` status. Valid from `active` or `paused` states. This action is irreversible.
         */
        post: operations["stopStreamV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/streams/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause a payment stream
         * @description Temporarily suspends an active stream, transitioning it to `paused` status. Payments are halted until the stream is resumed. Only valid when the stream is `active`.
         */
        post: operations["pauseStreamV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/streams/{id}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Settle a payment stream
         * @description Finalises the stream's payment balance and records settlement details. Can only be called on a stream in `ended` status. Populates the `settlement` field with amount, currency, and timestamp.
         */
        post: operations["settleStreamV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/dlq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive a dead-letter-queue webhook event
         * @description Accepts failed webhook events for reprocessing. No authentication required (secured at the network/gateway level).
         */
        post: operations["receiveDlqWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhook delivery attempts */
        get: operations["listWebhookDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Webhook delivery system health
         * @description Returns the health status of the webhook delivery system along with subscription and delivery statistics.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Health status retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Failed to retrieve health stats */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/webhooks/redeliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force-redeliver a webhook event
         * @description Creates a new delivery for an existing delivery ID, reusing the original endpoint and event payload.
         *
         *     **Auth:** Internal-service HMAC or admin JWT required.
         *
         *     **Data availability:** The original delivery must have full event/endpoint snapshots (deliveries created after snapshot support shipped).
         *
         *     **Idempotency:** Not enforced at the endpoint level; each call creates a new delivery.
         */
        post: operations["adminRedeliverWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/pause-by-sender": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emergency-pause all streams by sender
         * @description Pauses all active payment streams belonging to the given sender address. Gated by admin auth — only the configured admin address may call this.
         *
         *     Non-active streams (draft, paused, ended) are silently skipped.
         *
         *     **Auth:** Admin wallet address via `Actor-Wallet-Address` header or JWT.
         *
         *     **Idempotency:** Not enforced; repeat calls are safe (already-paused streams are skipped).
         */
        post: operations["adminPauseBySender"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/circuit-breaker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read circuit breaker state
         * @description Returns the current state of every named circuit breaker.
         *
         *     **Auth:** Admin wallet address via `Actor-Wallet-Address` header or JWT.
         */
        get: operations["adminGetCircuitBreakers"];
        put?: never;
        /**
         * Toggle an indexer or webhook circuit breaker
         * @description Trips or resets a named subsystem circuit breaker. Gated by admin auth — only the configured admin address may call this.
         *
         *     When `open` is true the named subsystem halts dispatch. For the `webhook` target this means no outbound delivery is attempted and the outbox drain is skipped; pending events are **held, not discarded**, and resume when the breaker is reset. For the `indexer` target the state is surfaced on `GET /api/indexer/status` as `breakerOpen`.
         *
         *     This global operator-controlled breaker is distinct from the automatic per-endpoint failure breaker, which trips itself after repeated delivery failures to a single endpoint and sends that endpoint's deliveries to the DLQ.
         *
         *     **Auth:** Admin wallet address via `Actor-Wallet-Address` header or JWT.
         *
         *     **Idempotency:** Naturally idempotent — setting the same state twice is a no-op beyond the updated timestamp.
         */
        post: operations["adminSetCircuitBreaker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/kms-sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign a payload via KMS (debug only)
         * @description **Non-production only.** Returns a base64-encoded signature for the given payload. Returns 403 in production.
         */
        post: operations["debugKmsSign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CircuitBreakerState: {
            /** @description True when the breaker is tripped and dispatch is halted. */
            open: boolean;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of the last toggle; null if never toggled.
             */
            updatedAt: string | null;
            /** @description Admin address that last toggled this breaker; null if never toggled. */
            updatedBy: string | null;
        };
        CircuitBreakers: {
            indexer: components["schemas"]["CircuitBreakerState"];
            webhook: components["schemas"]["CircuitBreakerState"];
        };
        ErrorEnvelope: {
            error: {
                /**
                 * @description Machine-readable error code.
                 * @example NOT_FOUND
                 */
                code: string;
                /**
                 * @description Human-readable description safe to display to clients.
                 * @example The requested stream does not exist.
                 */
                message: string;
                /**
                 * @description Opaque identifier for this request, useful for log correlation.
                 * @example req_01HZ9ABCDEF
                 */
                request_id: string;
            };
        };
        /** @description v1 payment stream shape. **Deprecated** — use `StreamV2` via `/api/v2/streams`. */
        StreamV1: {
            /**
             * @description Unique stream identifier.
             * @example stream-abc12345
             */
            id: string;
            /**
             * @description Stellar public key of the payment recipient.
             * @example GABC1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABCDEFG
             */
            recipient: string;
            /**
             * @description Numeric payment amount per schedule interval.
             * @example 120
             */
            rate: string;
            /**
             * @description Payment interval.
             * @example month
             * @enum {string}
             */
            schedule: "second" | "minute" | "hour" | "day" | "week" | "month" | "year";
            /**
             * @description Current lifecycle state of the stream.
             * @enum {string}
             */
            status: "draft" | "active" | "paused" | "ended";
            /**
             * @description The next permitted action for the authenticated user.
             * @example start
             */
            nextAction: string | null;
            /**
             * @description Stellar asset code.
             * @example XLM
             */
            token: string;
            /**
             * Format: date-time
             * @description ISO-8601 creation timestamp.
             * @example 2024-01-15T10:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description ISO-8601 last-updated timestamp.
             * @example 2024-01-15T10:00:00.000Z
             */
            updatedAt: string;
        };
        StreamV2: {
            /**
             * @description Unique stream identifier.
             * @example stream_lf3k9z
             */
            id: string;
            /**
             * @description Stellar public key of the payment recipient.
             * @example GABC1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABCDEFG
             */
            recipient: string;
            /**
             * @description Human-readable payment rate.
             * @example 120 XLM/month
             */
            rate: string;
            /**
             * @description Current lifecycle state of the stream.
             * @enum {string}
             */
            status: "draft" | "active" | "paused" | "ended";
            /**
             * @description Actions the authenticated user may perform on this stream. Replaces v1 `actions`.
             * @example [
             *       "pause",
             *       "stop"
             *     ]
             */
            allowed_actions: string[];
            /**
             * Format: date-time
             * @description ISO-8601 creation timestamp. Replaces v1 `createdAt`.
             * @example 2024-01-15T10:00:00.000Z
             */
            created_at: string;
            /** @description Settlement details once the stream has been settled, otherwise `null`. Clients must handle `null` explicitly. */
            settlement: {
                /**
                 * Format: date-time
                 * @example 2024-02-01T12:00:00.000Z
                 */
                settled_at: string;
                /** @example 360 XLM */
                amount: string;
                /** @example XLM */
                currency: string;
            } | null;
        };
        WalletChallenge: {
            /**
             * @description One-time nonce the client must sign with their Stellar private key.
             * @example streampay_auth_1716000000000_x7k2m
             */
            challenge: string;
            /**
             * Format: date-time
             * @description Challenge expiry (5 minutes from issuance).
             * @example 2024-01-15T10:05:00.000Z
             */
            expires_at: string;
        };
        WalletToken: {
            /**
             * @description Opaque bearer token. Pass as `Authorization: Bearer <token>`.
             * @example tok_R0FCQzEyMzQ1Njc4OTA
             */
            token: string;
            /**
             * Format: date-time
             * @description Token expiry (24 hours from issuance).
             * @example 2024-01-16T10:00:00.000Z
             */
            expires_at: string;
        };
        AuditActor: {
            id: string;
            /** @enum {string} */
            role: "user" | "support" | "admin" | "finance" | "security" | "compliance" | "system";
        };
        AuditTarget: {
            /** @enum {string} */
            type: "stream" | "account";
            id: string;
            account?: string;
        };
        AuditEntry: {
            id: string;
            actor: components["schemas"]["AuditActor"];
            target: components["schemas"]["AuditTarget"];
            action: string;
            beforeHash?: string | null;
            afterHash?: string | null;
            diffHash?: string | null;
            requestId: string;
            /** Format: date-time */
            timestamp: string;
            prevHash?: string | null;
            entryHash: string;
            /** Format: date-time */
            retentionUntil: string;
            metadata?: {
                [key: string]: string | number | boolean | null;
            };
        };
        AuditResponse: {
            access: {
                actorId: string;
                /** @enum {string} */
                role: "user" | "support" | "admin" | "finance" | "security" | "compliance" | "system";
            };
            data: components["schemas"]["AuditEntry"][];
            links: {
                self: string;
            };
            meta: {
                chainIntact: boolean;
                retentionDays: number;
                total: number;
            };
        };
        ActivityEvent: {
            /**
             * @description Unique event identifier.
             * @example evt_a1b2c3d4
             */
            id: string;
            /**
             * @description Event type classification.
             * @example stream.created
             */
            type: string;
            /**
             * @description Associated stream identifier, if applicable.
             * @example stream-abc12345
             */
            streamId?: string;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of the event.
             * @example 2026-04-28T09:00:00Z
             */
            timestamp: string;
            /**
             * @description Human-readable event description.
             * @example Stream 'Design Retainer' created and set to draft.
             */
            description: string;
        };
        PaginatedMeta: {
            /** @description Whether additional results are available. */
            hasNext: boolean;
            /**
             * @description Opaque base64-encoded cursor for the next page. Null when hasNext is false.
             * @example MjAyNi0wNC0yN1QyMDowMDowMFp8ZXZ0LTI=
             */
            nextCursor: string | null;
            /**
             * @description Total number of items matching the filter criteria.
             * @example 42
             */
            total: number;
        };
        ActivityResponse: {
            data: components["schemas"]["ActivityEvent"][];
            meta: components["schemas"]["PaginatedMeta"];
            links: {
                /**
                 * @description Canonical URL for this request.
                 * @example /api/activity?limit=20
                 */
                self: string;
            };
        };
    };
    responses: {
        /** @description Bad request — invalid input. */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "BAD_REQUEST",
                 *         "message": "Request body must include 'recipient' and 'rate'.",
                 *         "request_id": "req_01HZ9ABCDEF"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Unauthorized — missing or invalid bearer token. */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "Bearer token required.",
                 *         "request_id": "req_01HZ9ABCDEF"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Forbidden. */
        403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "This endpoint is not available in production.",
                 *         "request_id": "req_01HZ9ABCDEF"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Not found — the requested resource does not exist. */
        404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "STREAM_NOT_FOUND",
                 *         "message": "Stream 'stream-abc12345' not found.",
                 *         "request_id": "req_01HZ9ABCDEF"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Conflict — the operation is not valid for the current stream state. */
        409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "STREAM_INACTIVE_STATE",
                 *         "message": "Cannot delete a stream that is active or paused. Stop it first.",
                 *         "request_id": "req_01HZ9ABCDEF"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Unprocessable entity — request body failed schema validation. */
        422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_ERROR",
                 *         "message": "One or more fields are invalid.",
                 *         "request_id": "req_01HZ9ABCDEF"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Internal server error. */
        500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "INTERNAL_SERVER_ERROR",
                 *         "message": "An unexpected error occurred.",
                 *         "request_id": "req_01HZ9ABCDEF"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listActivity: {
        parameters: {
            query?: {
                /** @description Maximum number of events to return (1-100, default 20). */
                limit?: number;
                /** @description Opaque base64-encoded composite cursor (timestamp|id) for cursor-based pagination. Obtained from meta.nextCursor of the previous response. */
                cursor?: string;
                /** @description Filter events by associated stream identifier. */
                streamId?: string;
                /** @description Filter events by type (e.g. stream.created, wallet.connected). */
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of activity events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Unprocessable entity — malformed cursor. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Too many requests — rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                /** @description Number of records to return (1-250, default 50). */
                limit?: number;
                /** @description Filter by action. */
                action?: string;
                /** @description Filter by actor ID. */
                actorId?: string;
                /** @description Search query. */
                q?: string;
                /** @description Filter by request ID. */
                requestId?: string;
                /** @description Filter by actor role. */
                role?: string;
                /** @description Filter by target ID. */
                targetId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit log list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
            401: components["responses"]["401"];
            500: components["responses"]["500"];
        };
    };
    getWalletChallenge: {
        parameters: {
            query: {
                /** @description Stellar public key (G…, 56 characters). */
                address: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Challenge issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletChallenge"];
                };
            };
            400: components["responses"]["400"];
            /** @description IP rate limit exceeded for challenge issuance (20 req/min per IP). */
            429: {
                headers: {
                    /** @description Seconds until the client may retry. */
                    "Retry-After"?: number;
                    /** @description Correlation ID for this response. */
                    "x-request-id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "rate_limit_exceeded",
                     *         "message": "Too many requests. Please try again later.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    verifyWalletSignature: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Stellar public key.
                     * @example GABC1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABCDEFG
                     */
                    address: string;
                    /**
                     * @description The nonce returned by GET /api/auth/wallet.
                     * @example streampay_auth_1716000000000_x7k2m
                     */
                    challenge: string;
                    /**
                     * @description Base64-encoded Ed25519 signature of the challenge.
                     * @example dGVzdHNpZ25hdHVyZQ==
                     */
                    signature: string;
                };
            };
        };
        responses: {
            /** @description Token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletToken"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            /** @description IP rate limit exceeded for wallet login (5 req/min per IP). */
            429: {
                headers: {
                    /** @description Seconds until the client may retry. */
                    "Retry-After"?: number;
                    /** @description Correlation ID for this response. */
                    "x-request-id"?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "rate_limit_exceeded",
                     *         "message": "Too many requests. Please try again later.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    listStreams: {
        parameters: {
            query?: {
                /** @description Maximum number of streams to return (1–100, default 20). */
                limit?: number;
                /** @description Opaque pagination cursor from a previous response `meta.nextCursor` field. */
                cursor?: string;
                /** @description Filter results to streams with this status. */
                status?: "draft" | "active" | "paused" | "ended";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated stream list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StreamV1"][];
                        links: {
                            /** @example /api/v1/streams?limit=20 */
                            self: string;
                        };
                        meta: {
                            /** @example false */
                            hasNext: boolean;
                            /** @example null */
                            nextCursor: string | null;
                            /** @example 1 */
                            total: number;
                        };
                    };
                };
            };
            /** @description Malformed cursor. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_CURSOR",
                     *         "message": "Malformed cursor",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RATE_LIMIT_EXCEEDED",
                     *         "message": "Too many requests. Retry after 30 seconds.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    createStream: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key (UUID recommended) to make the request idempotent. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Stellar public key of the payment recipient (56-character G… address).
                     * @example GABC1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABCDEFG
                     */
                    recipient: string;
                    /**
                     * @description Positive decimal payment amount per schedule interval (max 7 decimal places).
                     * @example 120
                     */
                    rate: string;
                    /**
                     * @description Payment interval.
                     * @example month
                     * @enum {string}
                     */
                    schedule: "second" | "minute" | "hour" | "day" | "week" | "month" | "year";
                    /**
                     * @description Stellar asset code (optional, defaults to XLM).
                     * @example XLM
                     */
                    token?: string;
                };
            };
        };
        responses: {
            /** @description Stream created. Initial status is `draft`; call `POST /api/streams/{id}/start` to activate. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StreamV1"];
                        links: {
                            /** @example /api/v1/streams/stream-abc12345 */
                            self: string;
                        };
                    };
                };
            };
            400: components["responses"]["400"];
            /** @description Idempotency key reused with a different request body. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "IDEMPOTENCY_CONFLICT",
                     *         "message": "Idempotency key has been used with a different request.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            422: components["responses"]["422"];
            /** @description Rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RATE_LIMIT_EXCEEDED",
                     *         "message": "Too many requests. Retry after 30 seconds.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    searchStreams: {
        parameters: {
            query?: {
                /** @description Full-text search query term. */
                q?: string;
                /** @description Filter by stream status (draft, active, paused, ended, withdrawn, cancelled). */
                status?: "draft" | "active" | "paused" | "ended" | "withdrawn" | "cancelled";
                /** @description Filter by asset or token symbol. */
                asset?: string;
                /** @description Filter by sender address. */
                sender?: string;
                /** @description Filter by recipient. */
                recipient?: string;
                /** @description ISO-8601 creation date lower bound. */
                from?: string;
                /** @description ISO-8601 creation date upper bound. */
                to?: string;
                /** @description Maximum number of results to return (1-200, default 50). */
                limit?: number;
                /** @description Pagination offset (default 0). */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StreamV1"][];
                        meta: {
                            total: number;
                            limit: number;
                            offset: number;
                            count: number;
                            query: string | null;
                        };
                        links: {
                            self: string;
                        };
                    };
                };
            };
            400: components["responses"]["400"];
            /** @description Rate limit exceeded. */
            429: {
                headers: {
                    /** @description Seconds until the client may retry. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    getStream: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for multi-tenant isolation. Must be a non-empty string. */
                "x-tenant-id": string;
            };
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream found. */
            200: {
                headers: {
                    /** @description Whether the response was served from cache (`HIT`) or fetched from the data store (`MISS`). */
                    "X-Cache"?: "HIT" | "MISS";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StreamV1"];
                        links: {
                            /** @example /api/v1/streams/stream-abc12345 */
                            self: string;
                        };
                    };
                };
            };
            /** @description Missing or empty `x-tenant-id` header. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "MISSING_TENANT",
                     *         "message": "Tenant ID header is required",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: components["responses"]["404"];
            /** @description Rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RATE_LIMIT_EXCEEDED",
                     *         "message": "Too many requests. Retry after 30 seconds.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    updateStream: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for multi-tenant isolation. Must be a non-empty string. */
                "x-tenant-id": string;
            };
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "rate": "150"
                 *     }
                 */
                "application/json": {
                    /**
                     * @description New rate amount.
                     * @example 150
                     */
                    rate?: string;
                    /**
                     * @example month
                     * @enum {string}
                     */
                    schedule?: "second" | "minute" | "hour" | "day" | "week" | "month" | "year";
                    /**
                     * @description New asset code.
                     * @example USDC
                     */
                    token?: string;
                };
            };
        };
        responses: {
            /** @description Stream updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StreamV1"];
                    };
                };
            };
            /** @description Missing `x-tenant-id` header or invalid JSON body. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: components["responses"]["404"];
            /** @description Rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RATE_LIMIT_EXCEEDED",
                     *         "message": "Too many requests. Retry after 30 seconds.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    deleteStream: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for multi-tenant isolation. Must be a non-empty string. */
                "x-tenant-id": string;
            };
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream deleted. No response body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or empty `x-tenant-id` header. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "MISSING_TENANT",
                     *         "message": "Tenant ID header is required",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            /** @description Rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RATE_LIMIT_EXCEEDED",
                     *         "message": "Too many requests. Retry after 30 seconds.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    startStream: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for multi-tenant isolation. Must be a non-empty string. */
                "x-tenant-id": string;
                /** @description Client-generated key (UUID recommended) to make the request idempotent. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream started or resumed successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StreamV1"];
                    };
                };
            };
            /** @description Missing or empty `x-tenant-id` header. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "MISSING_TENANT",
                     *         "message": "Tenant ID header is required",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: components["responses"]["404"];
            /** @description Conflict — stream is not in `draft` or `paused` status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_STREAM_STATE",
                     *         "message": "Cannot start a stream that is not in draft or paused status.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RATE_LIMIT_EXCEEDED",
                     *         "message": "Too many requests. Retry after 30 seconds.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    stopStream: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for multi-tenant isolation. Must be a non-empty string. */
                "x-tenant-id": string;
                /** @description Client-generated key (UUID recommended) to make the request idempotent. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream stopped successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StreamV1"];
                    };
                };
            };
            /** @description Missing or empty `x-tenant-id` header. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "MISSING_TENANT",
                     *         "message": "Tenant ID header is required",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: components["responses"]["404"];
            /** @description Conflict — stream is not in `active` or `draft` status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_STREAM_STATE",
                     *         "message": "Only active or draft streams can be stopped.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RATE_LIMIT_EXCEEDED",
                     *         "message": "Too many requests. Retry after 30 seconds.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    pauseStream: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for multi-tenant isolation. Must be a non-empty string. */
                "x-tenant-id": string;
                /** @description Client-generated key (UUID recommended) to make the request idempotent. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream paused successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StreamV1"];
                    };
                };
            };
            /** @description Missing or empty `x-tenant-id` header. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "MISSING_TENANT",
                     *         "message": "Tenant ID header is required",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: components["responses"]["404"];
            /** @description Conflict — stream is not in `active` status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_STREAM_STATE",
                     *         "message": "Cannot pause a stream that is not active.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RATE_LIMIT_EXCEEDED",
                     *         "message": "Too many requests. Retry after 30 seconds.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    settleStream: {
        parameters: {
            query?: never;
            header: {
                /** @description Tenant context for multi-tenant isolation. Must be a non-empty string. */
                "x-tenant-id": string;
                /** @description Client-generated key (UUID recommended) to make the request idempotent. */
                "Idempotency-Key"?: string;
            };
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream settled successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StreamV1"];
                    };
                };
            };
            /** @description Missing or empty `x-tenant-id` header. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "MISSING_TENANT",
                     *         "message": "Tenant ID header is required",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            404: components["responses"]["404"];
            /** @description Conflict — stream is not in `active` or `paused` status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_STREAM_STATE",
                     *         "message": "Only active or paused streams can be settled.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "RATE_LIMIT_EXCEEDED",
                     *         "message": "Too many requests. Retry after 30 seconds.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
            /** @description Settlement failed — Stellar/Soroban transaction could not be completed. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "SETTLEMENT_FAILED",
                     *         "message": "Failed to settle stream on Stellar/Soroban",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listStreamsV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated stream list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        streams: components["schemas"]["StreamV2"][];
                    };
                };
            };
            401: components["responses"]["401"];
            500: components["responses"]["500"];
        };
    };
    createStreamV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Stellar public key of the recipient (56-character G… address).
                     * @example GABC1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABCDEFG
                     */
                    recipient: string;
                    /**
                     * @description Positive decimal payment amount per schedule interval (max 7 decimal places).
                     * @example 120
                     */
                    rate: string;
                    /**
                     * @description Payment interval.
                     * @example month
                     * @enum {string}
                     */
                    schedule: "second" | "minute" | "hour" | "day" | "week" | "month" | "year";
                    /**
                     * @description Stellar asset code (optional, defaults to XLM).
                     * @example XLM
                     */
                    token?: string;
                };
            };
        };
        responses: {
            /** @description Stream created. Initial status is `draft`. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "stream_lf3k9z",
                     *       "recipient": "GABC1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ234567890ABCDEFG",
                     *       "rate": "120 XLM/month",
                     *       "status": "draft",
                     *       "allowed_actions": [
                     *         "start"
                     *       ],
                     *       "created_at": "2024-01-15T10:00:00.000Z",
                     *       "settlement": null
                     *     }
                     */
                    "application/json": components["schemas"]["StreamV2"];
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            422: components["responses"]["422"];
            500: components["responses"]["500"];
        };
    };
    getStreamV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StreamV2"];
                        links: {
                            /** @example /api/v2/streams/stream_lf3k9z */
                            self: string;
                        };
                    };
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    deleteStreamV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream deleted. No response body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            409: components["responses"]["409"];
            500: components["responses"]["500"];
        };
    };
    startStreamV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream started successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamV2"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            /** @description Conflict — stream is not in `draft` status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_STATE_TRANSITION",
                     *         "message": "Cannot start a stream that is not in draft or paused status.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    stopStreamV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream stopped successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamV2"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            /** @description Conflict — stream is not in `active` or `paused` status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_STATE_TRANSITION",
                     *         "message": "Cannot stop a stream that is not active or paused.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    pauseStreamV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream paused successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamV2"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            /** @description Conflict — stream is not in `active` status. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_STATE_TRANSITION",
                     *         "message": "Cannot pause a stream that is not active.",
                     *         "request_id": "req_01HZ9ABCDEF"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    settleStreamV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stream identifier. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream settled successfully. The `settlement` field is now populated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamV2"];
                };
            };
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            /** @description Conflict — stream is not in `ended` status or has already been settled. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            500: components["responses"]["500"];
        };
    };
    receiveDlqWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Event accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        received: boolean;
                    };
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    listWebhookDeliveries: {
        parameters: {
            query?: {
                /** @description Number of records to return (1–100, default 20). */
                limit?: number;
                /** @description Opaque pagination cursor from a previous response. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delivery list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        deliveries: Record<string, never>[];
                        cursor: string | null;
                        limit: number;
                    };
                };
            };
            400: components["responses"]["400"];
            500: components["responses"]["500"];
        };
    };
    adminRedeliverWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The delivery ID to reissue.
                     * @example del-01HZ9ABCDEF
                     */
                    deliveryId: string;
                };
            };
        };
        responses: {
            /** @description Redelivery enqueued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description The ID of the newly created delivery. */
                            deliveryId: string;
                            /** @description The original delivery ID that was reissued. */
                            originalDeliveryId: string;
                        };
                        links?: {
                            /** @description URL to query this delivery's status. */
                            delivery?: string;
                        };
                    };
                };
            };
            400: components["responses"]["400"];
            401: components["responses"]["401"];
            404: components["responses"]["404"];
            500: components["responses"]["500"];
        };
    };
    adminPauseBySender: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Stellar wallet address of the sender whose streams should be paused.
                     * @example GCVVMU4QAB7O6TZCZMF4FPL2KOHVPR2SJNX5O3H6X5Y5QK6HZ
                     */
                    senderAddress: string;
                };
            };
        };
        responses: {
            /** @description Streams paused. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description Array of streams that were paused by this request. */
                            paused: components["schemas"]["StreamV1"][];
                            /** @description Number of streams paused. */
                            count: number;
                            /** @description The sender address that was targeted. */
                            senderAddress: string;
                        };
                    };
                };
            };
            400: components["responses"]["400"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
            500: components["responses"]["500"];
        };
    };
    adminGetCircuitBreakers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current breaker state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CircuitBreakers"];
                    };
                };
            };
            403: components["responses"]["403"];
            500: components["responses"]["500"];
        };
    };
    adminSetCircuitBreaker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Which subsystem breaker to toggle.
                     * @example webhook
                     * @enum {string}
                     */
                    target: "indexer" | "webhook";
                    /**
                     * @description true trips the breaker (halt dispatch); false resets it (resume).
                     * @example true
                     */
                    open: boolean;
                };
            };
        };
        responses: {
            /** @description Breaker updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CircuitBreakers"];
                    };
                };
            };
            400: components["responses"]["400"];
            403: components["responses"]["403"];
            422: components["responses"]["422"];
            500: components["responses"]["500"];
        };
    };
    debugKmsSign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Base64-encoded data to sign.
                     * @example aGVsbG8=
                     */
                    payload: string;
                };
            };
        };
        responses: {
            /** @description Signature produced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Base64-encoded signature.
                         * @example c2lnbmVkOmFHVnNiRzg5
                         */
                        signature: string;
                    };
                };
            };
            400: components["responses"]["400"];
            403: components["responses"]["403"];
            500: components["responses"]["500"];
        };
    };
}
